### ISSUE TITLE
ModuleNotFoundError: No module named 'crytic_compile'

### ISSUE THREAD

**Issue by Ajeeshb** [enzymefinance/oyente#429]
While starting the docker container i am getting the below error.

```
root@testing:/home/ubuntu/oyente/oyente# docker run -it -p 3000:3000 -e "OYENTE=/oyente/oyente" oyente:latest
Traceback (most recent call last):
  File "/oyente/oyente/oyente.py", line 14, in <module>
    from input_helper import InputHelper
  File "/oyente/oyente/input_helper.py", line 11, in <module>
    from crytic_compile import CryticCompile, InvalidCompilation
ModuleNotFoundError: No module named 'crytic_compile'
```

**Comment by yagol2020** [comment]
you may need to install [crytic-compile](https://github.com/crytic/crytic-compile) in docker container

> pip install crytic-compile

**Comment by qub1tt** [comment]
> you may need to install [crytic-compile](https://github.com/crytic/crytic-compile) in docker container
> 
> > pip install crytic-compile

after i installed the package it has this error AttributeError: 'CryticCompile' object has no attribute 'contracts_names'.
Im using python 3.10.4.
